
---

- hosts: all
  become: true # equiv: sudo;
  tasks:

  - name: remove apache2
    apt: # command we're using (Debian / ubuntu)
      name: apache2
      state: absent
  
  - name: apache prerequisites
    apt:
      name: libapache2-mod-php
      state: absent

# CMD : ansible-playbook --ask-become-pass remove_apache.yml
